import type { PageCollectionItemBase, DataCollectionItemBase } from '@nuxt/content'

declare module '@nuxt/content' {
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface ContentCollectionItem extends PageCollectionItemBase {}
  
   /* eslint-disable */
  /**
   * This file was automatically generated by json-schema-to-typescript.
   * DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
   * and run json-schema-to-typescript to regenerate this file.
   */
  
  interface RecipesCollectionItem extends PageCollectionItemBase {
    title: string;
    description: string;
    description_long?: string;
    image?: string;
    ingredients:
    | string[]
    | {
      [k: string]: string[];
      };
    instructions: string[];
    created: string;
    tags?: string[];
    categories?: string[];
  }
  

  interface PageCollections {
    content: ContentCollectionItem
    recipes: RecipesCollectionItem
  }

  interface Collections {
    content: ContentCollectionItem
    recipes: RecipesCollectionItem
  }
}
